version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9092:9090"  # Changed to avoid conflicts
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  # Changed from 3000 to 3001

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9102:9100"  # Changed from 9100 to 9102
